
build:
  version:
    3.0

loans:
  message: "Welcome to the EazyBank accounts related to QA APIs"
  contactDetails:
    name: "Neela Natarajan - QA Lead"
    email: "neelanatarajan15292@gmail.com"
  onCallSupport:
    -(555) 955-1234
    -(555) 655-6789